#!/usr/bin/env bash

set -euo pipefail

ROOT_DIRECTORY="$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )"
readonly ROOT_DIRECTORY

cd "${ROOT_DIRECTORY}"

GOOD_FILE='./test-good.js'
ORIGINAL_FILE='./test-original.js'
TEMPORARY_FILE="$(mktemp "/tmp/temp.XXX.js")"
TEST_RESULT=0

cp "${ORIGINAL_FILE}" "${TEMPORARY_FILE}"

./to_multi_var "${TEMPORARY_FILE}"

if diff "${TEMPORARY_FILE}" "${GOOD_FILE}"; then
    echo '✓ TEST PASSED! File contents matched.'
else
    echo
    echo "✗ TEST FAILED! See contents' difference above."
    test_result=1
fi

rm "${TEMPORARY_FILE}"

exit "${TEST_RESULT}"
