#!/usr/bin/env bash

ROOT_DIRECTORY="$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )"
readonly ROOT_DIRECTORY

convert_file() {
    local file=$@

    echo "→ Converting var declarations in: ${file}"
    vim -u "${ROOT_DIRECTORY}/vimrc" \
        -e -s \
        -S "${ROOT_DIRECTORY}/autoload/to_multi_var.vim" \
        +SingleToMultiVar \
        +update \
        +q \
        "${file}"
}

convert_directory() {
    local dir=$@
    local file

    echo "Recursing in the directory: ${dir}"
    find "${dir}" \
        -type f \
        -not -path "*/node_modules/*" \
        -not -path "*/vendor/*" \
        -iregex ".*\.js$" \
    | while read file; do
        convert_file "${file}"
    done
}

# If no arg passed, recurse current dir:
if [ $# = 0 ]; then
    convert_directory .
    exit 0
fi

# Accepts multiple args, both files or directories:
while [[ $# > 0 ]]; do
    if [ -n "$1" ] && [ -f "$1" ]; then
        convert_file "$1"
    elif [ -d "$1" ]; then
        convert_directory "$1"
    fi
    shift
done

exit 0
