#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

convertFile() {
    file=$@
    echo "→ Converting var declarations in: $file"
    vim -u "$SCRIPT_DIR/vimrc" \
        -e -s \
        -S "$SCRIPT_DIR/autoload/to_multi_var.vim" \
        +SingleToMultiVar \
        +update \
        +q \
        "$file"
}

convertDir() {
    dir=$@
    echo "Recursing in the directory: $dir"
    find "$dir" \
        -type f \
        -not -path "*/node_modules/*" \
        -not -path "*/vendor/*" \
        -iregex ".*\.js$" \
    | while read file; do
        convertFile $file
    done
}

# If no arg passed, recurse current dir:
if [ $# = 0 ]; then
    convertDir .
    exit 0
fi

# Accepts multiple args, both files or directories:
while [[ $# > 0 ]]; do
    if [ -n "$1" ] && [ -f "$1" ]; then
        convertFile "$1"
    elif [ -d "$1" ]; then
        convertDir "$1"
    fi
    shift
done

exit 0
